services:
  - type: web
    name: translation-microservice
    env: docker
    plan: free
    repo: https://github.com/tarakantaacharya/Udaanproject.git
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
